import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import AppProvider from '@/store/Provider';
import './globals.css';
import ToastProvider from '@/components/toaster';
import { store } from '@/store';
import { loginUser } from '@/store/features/auth-slice';
import AuthProvider from '@/components/AuthProvider';
const inter = Poppins({
  weight: ['100', '300', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppProvider>
      {/* <AuthProvider> */}
      <html lang='en'>
        <body className={` ${inter.className}`}>
          <ToastProvider />
          {children}
        </body>
      </html>
      {/* </AuthProvider> */}
    </AppProvider>
  );
}
