import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import AppProvider from '@/store/Provider';
import './globals.css';
import ToastProvider from '@/components/toaster';
import { store } from '@/store';
import { loginUser } from '@/store/features/auth-slice';
import AuthProvider from '@/components/AuthProvider';
const inter = Poppins({
  weight: ['100', '300', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // await store.dispatch(
  //   loginUser({ email: 'mohamed@gmail.com', password: '!Aa123456789' })
  // );
  return (
    <AppProvider>
      <html lang='en'>
        <body className={` ${inter.className}`}>
          <AuthProvider>
            <ToastProvider />
            {children}
          </AuthProvider>
        </body>
      </html>
    </AppProvider>
  );
}
